spring:

  datasource:
    url: jdbc:mysql://localhost:3306/bt_database
    username: root
    password: nyang
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true